# Generated by Django 4.0 on 2021-12-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='img',
        ),
    ]
