# Generated by Django 4.0 on 2021-12-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='youtube',
        ),
        migrations.AddField(
            model_name='teacher',
            name='social',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
